insert into public."Author"("Author_Name" ) values('Jodi Picoult');
insert into public."Author"("Author_Name" ) values('Judith Goudge');
insert into public."Author"("Author_Name" ) values('Geling Yan');
insert into public."Author"("Author_Name" ) values('Nhiều tác giả');
insert into public."Author"("Author_Name" ) values('Natsuki Amasawa');
insert into public."Author"("Author_Name" ) values('Phương Nam');
insert into public."Author"("Author_Name" ) values('Nghê Đa Hỉ');
insert into public."Author"("Author_Name" ) values('Donald J. Trump');
insert into public."Author"("Author_Name" ) values('Trần Văn Khê');
insert into public."Author"("Author_Name" ) values('Robert T. Kiyosaki');
insert into public."Author"("Author_Name" ) values('Brican Tracy');
insert into public."Author"("Author_Name" ) values('Kevin Kruse');
insert into public."Author"("Author_Name" ) values('Dottie Schindlinger');
insert into public."Author"("Author_Name" ) values('Robin Sharma');
insert into public."Author"("Author_Name" ) values('Matt Fortnow');
insert into public."Author"("Author_Name" ) values('PSG. TS Phạm Văn Dược');
insert into public."Author"("Author_Name" ) values('Huy Hoàng');
insert into public."Author"("Author_Name" ) values('Nguyễn Trung Tánh - Phạm Tấn Quyền');
insert into public."Author"("Author_Name" ) values('Ken Xiao');
insert into public."Author"("Author_Name" ) values('The Sakura');
insert into public."Author"("Author_Name" ) values('Jim Glesson');
insert into public."Author"("Author_Name" ) values('Hoàng Quỳnh');
insert into public."Author"("Author_Name" ) values('Michael L. Kluemper');
insert into public."Author"("Author_Name" ) values('Phạm Tuyết Trinh');
insert into public."Author"("Author_Name" ) values('Việt Fame');
insert into public."Author"("Author_Name" ) values('Trần Minh Quới');
insert into public."Author"("Author_Name" ) values('Thái Quang Vinh');
insert into public."Author"("Author_Name" ) values('Nguyễn Thị Thanh Trúc');
insert into public."Author"("Author_Name" ) values('Trang Anh');
insert into public."Author"("Author_Name" ) values('Eiichiro Oda');
insert into public."Author"("Author_Name" ) values('Yoshito Usui');
insert into public."Author"("Author_Name" ) values('Gosho Aoyama');
insert into public."Author"("Author_Name" ) values('Masashi Kishimoto');
insert into public."Author"("Author_Name" ) values('Negi Haruba');
insert into public."Author"("Author_Name" ) values('Tomohito Oda');
insert into public."Author"("Author_Name" ) values('Lê Linh');
insert into public."Author"("Author_Name" ) values('Neil Degrasse Tyson');
insert into public."Author"("Author_Name" ) values('Bill Bryson');
insert into public."Author"("Author_Name" ) values('Nguyễn Văn Tuệ');
insert into public."Author"("Author_Name" ) values('Phạm Quang Huy');
insert into public."Author"("Author_Name" ) values('Nguyễn Đình Phú');
insert into public."Author"("Author_Name" ) values('Louise Edington');
insert into public."Author"("Author_Name" ) values('Randy Lynn');
insert into public."Author"("Author_Name" ) values('Cheiro');
insert into public."Author"("Author_Name" ) values('Kim Sang Kyun');
insert into public."Author"("Author_Name" ) values('Pegasus');
insert into public."Author"("Author_Name" ) values('Nguyễn Hùng Cường');
insert into public."Author"("Author_Name" ) values('Đinh Văn Quế');
insert into public."Author"("Author_Name" ) values('Lâm Quốc Tuấn');
insert into public."Author"("Author_Name" ) values('Quốc Hội');

insert into public."Category"("Category_Name" ) values('Sách văn học');
insert into public."Category"("Category_Name" ) values('Sách kinh tế');
insert into public."Category"("Category_Name" ) values('Sách ngoại ngữ');
insert into public."Category"("Category_Name" ) values('Sách tham khảo');
insert into public."Category"("Category_Name" ) values('Truyện tranh');
insert into public."Category"("Category_Name" ) values('Sách khoa học');
insert into public."Category"("Category_Name" ) values('Sách chính trị');
insert into public."Category"("Category_Name" ) values('Tạp chí');