DROP TABLE IF EXISTS "Admin";
DROP TABLE IF EXISTS "Contact_Lib";
DROP TABLE IF EXISTS "Request";
DROP TABLE IF EXISTS "ReqHistory";
DROP TABLE IF EXISTS "Comment";
DROP TABLE IF EXISTS "Order";
DROP TABLE IF EXISTS "Book";
DROP TABLE IF EXISTS "Library";
DROP TABLE IF EXISTS "User";

