DROP TABLE IF EXISTS "Admin";
DROP TABLE IF EXISTS "Contact_Lib";
DROP TABLE IF EXISTS "Comment";
DROP TABLE IF EXISTS "Order";
DROP TABLE IF EXISTS "Library";
DROP TABLE IF EXISTS "Category";
DROP TABLE IF EXISTS "Author";
DROP TABLE IF EXISTS "User";

